"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[░▒▓](color1)[󰣇](fg:#090c0c bg:color1)$username[](bg:color6 fg:color1)$directory[](fg:color11 bg:color6)$git_branch$git_status[](fg:color6 bg:color6)$nodejs$rust$golang$php[](fg:color6 bg:color12)$conda[ ](fg:color12)$line_break$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '#8fcef3'
color2 = '#003549'
color3 = '#c0c7cd'
color4 = '#1c2023'
color5 = '#003549'
color6 = '#003549'
color7 = '#0f1417'
color8 = '#8fcef3'
color9 = '#cac1e9'
color10 = '#001e2c'
color11 = '#004c69'
color12 = '#20333e'


[username]
show_always = true
style_user = "fg:#090c0c bg:color1 "
style_root = "fg:#090c0c bg:color1 "
format = "[ $user ]($style)"
disabled = false


[directory]
style = "fg:color3 bg:color11"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:color6"
format = '[[ $symbol $branch ](fg:color1 bg:color6)]($style)'

[git_status]
style = "bg:color6"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:color6)]($style)'

[nodejs]
symbol = ""
style = "bg:color11"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:color11)]($style)'

[rust]
symbol = ""
style = "bg:color11"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:color11)]($style)'

[golang]
symbol = ""
style = "bg:color11"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:color11)]($style)'

[php]
symbol = ""
style = "bg:color11"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:color11)]($style)'

[conda]
symbol = " "
style = "bg:color12"
format = '[ $symbol$environment ](fg:#a0a9cb bg:color12)'
ignore_base = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color12"
format = '[[  $time ](fg:#a0a9cb bg:color12)]($style)'

