cursor #f1dedd
cursor_text_color #d8c2c0

foreground            #f1dedd
# background            #141414
selection_foreground  #442928
selection_background  #e7bdb9
url_color             #ffb3ae

# black
# color8   #585252
# color0   #4c4c4c

# red
color1   #b8545b
color9   #b15b5f

# green
color2   #ffb3ae
color10  #ffb3ae

# yellowwa
color3   #b1aa63
color11  #beb769

# blue
/* color4  #776dafff */
color4  #ffb3ae
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #c49ec4

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
