[color_adjustment]
saturation = 0
contrast = 1.5


[config.wallpaper]
command = "hyprpaper"
set = false
arguments = ["img", "--transition-type", "center"]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors/colors.conf'


[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors/colors-matugen.rasi'


[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'


[templates.swaync]
input_path = '~/.config/matugen/templates/colors-swaync.css'
output_path = '~/.config/swaync/colors-swaync.css'


[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'


[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.chrome]
input_path = '/home/noro18/.config/matugen/templates/chromium-theme.json'
output_path = '/home/noro18/.config/chromium/Default/Extensions/Matugen-theme/manifest.json'

# PywalFox bridge (for Zen Browser UI via PywalZen)
# [templates.pywalfox]
# input_path  = "~/.config/matugen/templates/pywalfox-colors.json"
# output_path = "~/.config/matugen/generated/pywalfox-colors.json"
# post_hook   = '''
# bash -c '{
#   mkdir -p "$HOME/.cache/wal"
#   ln -nfs "$HOME/.config/matugen/generated/pywalfox-colors.json" "$HOME/.cache/wal/colors.json"
#   pywalfox update
# } >/dev/null 2>&1 & disown'
# '''

# Website colors (userContent.css)
[templates.zen-colors]
input_path  = "~/.config/matugen/templates/zen-colors.css"
output_path = "/home/noro18/.zen/6ehkzul9.Default (release)/chrome/colors.css"

[templates.pywalfox]
input_path  = "~/.config/matugen/templates/pywalfox-colors.json"
output_path = "~/.config/matugen/generated/pywalfox-colors.json"
post_hook   = '''
bash -c '
{
  if command -v pywalfox >/dev/null 2>&1; then
    mkdir -p "$HOME/.cache/wal"
    ln -nfs "$HOME/.config/matugen/generated/pywalfox-colors.json" "$HOME/.cache/wal/colors.json"
    pywalfox update
  fi
} >/dev/null 2>&1 </dev/null & disown
'
'''
